### PR TITLE
fix: CReset config prop type

### PR DESCRIPTION
**Pull request by freality**
Providing a config prop to `CReset` results in `[Vue warn]: Invalid prop: type check failed for prop "config". Expected Object, got Function` when a Function is passed in.

## Description
Changed config prop type from `Object` to `Function`.

## Motivation and Context

Resolves Issue: #283 

## How Has This Been Tested?
No testing included.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by codebender828 — APPROVED** [review]
Thank you @freality

**Comment by codebender828** [comment]
Hey, @freality. I noticed this pull request was still a draft and I marked it as ready for review by accident. Are you adding any more work to this PR?

I think a good addition would be some simple tests for this component since it doesn't actually have some tests yet. 👍🏽

**Comment by freality** [comment]
@codebender828 No. I wasn't aware that a draft would be public. I just wanted to submit the fix in this PR.

I've not written tests for a Vue component like this before. So, I'm looking through your `CThemeProvider` tests to learn. I'll submit the tests as a separate PR.

**Comment by codebender828** [comment]
Great! Thank you. 

Then I'll go ahead and merge this. If you want to add a tests, I would recommend using an example of the `CBox.test.js` because it uses the `@testing-library/vue` package which is generally more declarative and easy to read for other contribtors. :)

The reason I recommend it is because the `CThemeProvider` was probably the first component test I ever wrote so I would not use it a first class example. 😅

**Comment by codebender828** [comment]
@all-contributors please add @freality for code.

**Pull request merged**
