### PR TITLE
docs: Added installation instruction for npm

### PR DESCRIPTION
**Pull request by AsaoluElijah**
## Description
Not everybody uses yarn so it would be useful to explicitly state the installation instruction via npm too.

## Types of changes
- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] My code follows the code style of this project.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by codebender828 — APPROVED** [review]
Thank you @AsaoluElijah

**Review by codebender828 — COMMENTED** [review]
Thanks for this @AsaoluElijah 

I think that in the future, maybe we should have a component that can toggle between Yarn and NPM in the docs so as to eliminate the redundancy between `yarn add` and `npm install`. Something like this:

image


Any thoughts? @dombavetta 

I am more on the side of keeping it as is, since there aren't many complaints about it.

**Comment by dombavetta** [comment]
@codebender828  I like the idea oh having tabs for yarn/npm. This in pretty common across many doc sites. The component would only apply to a very small use case right now, branching a little off topic here, but may be useful in the future if we need to show specific code examples for say vue 3 composition api vs options api.

**Comment by codebender828** [comment]
Hey @AsaoluElijah .

Thank you so much for the contribution on this. 🙏🏽

I'll be closing this pull request in preferrence for #341 opened by @dombavetta.

**Comment by AsaoluElijah** [comment]
No problem @codebender828 . 
The toggle looks quite better 🎉

**Pull request closed without merging**
