### PR TITLE
feat(image): Add srcset support to CImage

### LINKED ISSUE #422: Properly support srcSet in the c-image component
**Is your feature request related to a problem? Please describe.**
I'm trying to optimize our site for mobile users. Using responsive images via nuxt-responsive-loader.
While this seems to work fine in the first moment. I realized it actually loaded 2 image versions. 
After digging the code I saw that chakra image uses a virtual image in it's code to detect if it should display the fallback image instead. 
However this virtual image doesn't take the srcset into account. Which means it directly loads the src image. (Which I provided additionally as a fallback for older browsers)

**Describe the solution you'd like**+
Give the c-image component proper srcset support by also giving the virtual img the srcset attribute.

**Additional context**
Screenshot of the network tab showing that more than 1 image was loaded.
image

Example coding for one image
image

### PR DESCRIPTION
**Pull request by MWFIAE**
Fixes #422

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by codebender828 — COMMENTED** [review]
Great. thanks @MWFIAE  Looks good to me! Gonna run tests and merge.

**Review by codebender828 — CHANGES_REQUESTED** [review]
Code looks good here @MWFIAE 

Would you like to include a test to make sure that the `srcset` attribute is covered as well?
Something along these lines?

```js
it('fallback src works', async () => {
  renderComponent({ template: '<CImage alt="My Image Description" src="IMAGE_SRC" srcset="IMAGE_SRCSET" />' })
  await wait(() => {
    expect(screen.getByAltText(/My Image Description/i)).toHaveAttribute('srcset', 'IMAGE_SRCSET')
  })
})
```

**Comment by MWFIAE** [comment]
@codebender828 Can you please take another look? :)

**Review by codebender828 — APPROVED** [review]
Thank you @MWFIAE

**Comment by MWFIAE** [comment]
Hi any news? @codebender828

**Comment by codebender828** [comment]
@all-contributors please add @MWFIAE for code, tests

**Pull request merged**
