### PR TITLE
feat: Adds CGridItem

### PR DESCRIPTION
**Pull request by IHIutch**
Create a `CGridItem` [like so ](https://chakra-ui.com/docs/layout/grid#griditem-props)

## Description
Adds `CGridItem`, modifies some imports/exports of `CGrid`

## Motivation and Context
Consistency with the react lib and greater control over grid items using Chakra consistent props

## How Has This Been Tested?
- Storybook
- Added new tests

## Screenshots (if appropriate):

image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by codebender828** [comment]
Hey @IHIutch !

Thanks for working on this PR. Juat wanted to.check with you if it's still in progress.

The code looks good to me. 👍🏽 The only thing missing here is a couple of tests. A couple of snapshots will suffice here. You can also look at the `CGrid.test.js` file to see some existing examples of how to test CSS property values on components.

**Comment by IHIutch** [comment]
Yep, still in progress. Probably will update this weekend. I'll keep you posted, thanks for checking in!

**Comment by IHIutch** [comment]
Wow, long weekend, eh? Anyway.. Updated this with tests and new documentation. Let me know what you think

**Comment by codebender828** [comment]
Thanks @IHIutch !

**Review by codebender828 — APPROVED** [review]
Thank you @IHIutch Looks great. Planning a new release tomorrow

**Pull request merged**
