### PR TITLE
fix(menu): update MenuOption defaultValue prop to inner value

### PR DESCRIPTION
**Pull request by abelnnieva**
## Description
Fixed a bug in the defaultValue prop of the MenuOption.

## Motivation and Context
The MenuOption is not using the value of the defaultValue prop. Also, for the checkbox type, the defaultValue prop must include the Array type.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by peoray** [comment]
@abelnnieva Thank you for spotting the issue and offering a PR. 
Quick question, what do you mean by the `checkbox type`?

**Comment by codebender828** [comment]
> @abelnnieva Thank you for spotting the issue and offering a PR.
> Quick question, what do you mean by the `checkbox type`?

I think he refers to this ⬇️ 

image

https://vue.chakra-ui.com/menu#menu-option-groups

**Review by codebender828 — APPROVED** [review]
Thank you @abelnnieva

**Comment by abelnnieva** [comment]
> @abelnnieva Thank you for spotting the issue and offering a PR.
> Quick question, what do you mean by the `checkbox type`?

@peoray It is the `type` property of the CMenuOptionGroup which can be `radio` or `checkbox`.

**Comment by codebender828** [comment]
@all-contributors please add @abelnnieva for bugs, code

**Pull request merged**
